const ONLINE = 'online';
const OFFLINE = 'offline';

const NOTIFICATION_FRIEND_REQUEST = 'friend_request';
const NOTIFICATION_FRIEND_ACCEPTED = 'friend_request_accepted';
const NOTIFICATION_GROUP_INVITATION = 'group_invitation';
const NOTIFICATION_GROUP_JOINTED = 'group_joined';
const NOTIFICATION_REPLY_MESSAGE = 'reply_message';
const NOTIFICATION_MENTION = 'mention';
const NOTIFICATION_REMOVE_FROM_CONVERSATION = 'remove_from_conversation';
const NOTIFICATION_CHANGE_ADMIN_ROLE = 'change_admin_role';
const NOTIFICATION_CHANGE_MEMBER_ROLE = 'change_member_role';
const NOTIFICATION_MENTIONED = 'mentioned';

const TEMP_NOTIFICATION_FRIEND_ACCEPTED = 'temp_friend_request_accepted';
const TEMP_NOTIFICATION_FRIEND_REJECTED = 'temp_friend_request_rejected';

const TEMP_NOTIFICATION_GROUP_INVITATION_ACCEPTED = 'temp_group_invitation_accepted';
const TEMP_NOTIFICATION_GROUP_INVITATION_REJECTED = 'temp_group_invitation_rejected';

const FRIEND_REQUEST_ACCEPTED = 'accepted';
const FRIEND_REQUEST_REJECTED = 'rejected';

const GROUP_INVITATION_ACCEPTED = 'accepted';
const GROUP_INVITATION_REJECTED = 'rejected';

const REPLY_ATTACHMENT = 'Attachment';
const REPLY_IMAGE_ATTACHMENT = 'ImageAttachment';
const REPLY_MESSAGE = 'Message';

const REACTION_TYPE_HAHA = 'haha';
const REACTION_TYPE_LIKE = 'like';
const REACTION_TYPE_LOVE = 'love';
const REACTION_TYPE_CARE = 'care';
const REACTION_TYPE_ANGRY = 'angry';
const REACTION_TYPE_SAD = 'sad';
const REACTION_TYPE_WOW = 'wow';

const CONVERSATION_PARTICIPANT_ROLE_CREATOR = 'creator';
const CONVERSATION_PARTICIPANT_ROLE_MEMBER = 'member';
const CONVERSATION_PARTICIPANT_ROLE_ADMIN = 'admin';

export {
    ONLINE,
    OFFLINE,
    NOTIFICATION_FRIEND_REQUEST,
    NOTIFICATION_FRIEND_ACCEPTED,
    NOTIFICATION_GROUP_INVITATION,
    NOTIFICATION_GROUP_JOINTED,
    NOTIFICATION_REPLY_MESSAGE,
    NOTIFICATION_MENTION,
    NOTIFICATION_REMOVE_FROM_CONVERSATION,
    NOTIFICATION_CHANGE_ADMIN_ROLE,
    NOTIFICATION_CHANGE_MEMBER_ROLE,
    NOTIFICATION_MENTIONED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    TEMP_NOTIFICATION_FRIEND_ACCEPTED,
    TEMP_NOTIFICATION_FRIEND_REJECTED,
    TEMP_NOTIFICATION_GROUP_INVITATION_ACCEPTED,
    TEMP_NOTIFICATION_GROUP_INVITATION_REJECTED,
    REPLY_ATTACHMENT,
    REPLY_IMAGE_ATTACHMENT,
    REPLY_MESSAGE,
    REACTION_TYPE_HAHA,
    REACTION_TYPE_LIKE,
    REACTION_TYPE_LOVE,
    REACTION_TYPE_CARE,
    REACTION_TYPE_ANGRY,
    REACTION_TYPE_SAD,
    REACTION_TYPE_WOW,
    GROUP_INVITATION_ACCEPTED,
    GROUP_INVITATION_REJECTED,
    CONVERSATION_PARTICIPANT_ROLE_CREATOR,
    CONVERSATION_PARTICIPANT_ROLE_MEMBER,
    CONVERSATION_PARTICIPANT_ROLE_ADMIN,
};
