const ONLINE = 'online';
const OFFLINE = 'offline';

const NOTIFICATION_FRIEND_REQUEST = 'friend_request';
const NOTIFICATION_FRIEND_ACCEPTED = 'friend_request_accepted';
const NOTIFICATION_GROUP_INVITATION = 'group_invitation';
const NOTIFICATION_GROUP_JOINTED = 'group_joined';
const NOTIFICATION_REPLY_MESSAGE = 'reply_message';
const NOTIFICATION_MENTION = 'mention';
const TEMP_NOTIFICATION_FRIEND_ACCEPTED = 'temp_friend_request_accepted';
const TEMP_NOTIFICATION_FRIEND_REJECTED = 'temp_friend_request_rejected';

const FRIEND_REQUEST_ACCEPTED = 'accepted';
const FRIEND_REQUEST_REJECTED = 'rejected';

const REPLY_ATTACHMENT = 'Attachment';
const REPLY_IMAGE_ATTACHMENT = 'ImageAttachment';
const REPLY_MESSAGE = 'Message';

export {
    ONLINE,
    OFFLINE,
    NOTIFICATION_FRIEND_REQUEST,
    NOTIFICATION_FRIEND_ACCEPTED,
    NOTIFICATION_GROUP_INVITATION,
    NOTIFICATION_GROUP_JOINTED,
    NOTIFICATION_REPLY_MESSAGE,
    NOTIFICATION_MENTION,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    TEMP_NOTIFICATION_FRIEND_ACCEPTED,
    TEMP_NOTIFICATION_FRIEND_REJECTED,
    REPLY_ATTACHMENT,
    REPLY_IMAGE_ATTACHMENT,
    REPLY_MESSAGE,
};
