const ONLINE = 'online';
const OFFLINE = 'offline';

const NOTIFICATION_FRIEND_REQUEST = 'friend_request';
const NOTIFICATION_FRIEND_ACCEPTED = 'friend_request_accepted';
const NOTIFICATION_GROUP_INVITATION = 'group_invitation';
const NOTIFICATION_GROUP_JOINTED = 'group_joined';
const NOTIFICATION_REPLY_MESSAGE = 'reply_message';
const NOTIFICATION_MENTION = 'mention';

export {
    ONLINE,
    OFFLINE,
    NOTIFICATION_FRIEND_REQUEST,
    NOTIFICATION_FRIEND_ACCEPTED,
    NOTIFICATION_GROUP_INVITATION,
    NOTIFICATION_GROUP_JOINTED,
    NOTIFICATION_REPLY_MESSAGE,
    NOTIFICATION_MENTION,
};
